apiVersion: apps/v1
kind: Deployment
metadata:
  name: prowlarr
  labels:
    app: prowlarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prowlarr
  template:
    metadata:
      labels:
        app: prowlarr
    spec:
      containers:
        - name: prowlarr
          image: lscr.io/linuxserver/prowlarr:latest
          envFrom:
            - configMapRef:
                name: prowlarr-config
          volumeMounts:
            - name: config-volume
              mountPath: /config
          ports:
            - containerPort: 9696
          livenessProbe:
            httpGet:
              path: /prowlarr/ping
              port: 9696
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /prowlarr/ping
              port: 9696
            initialDelaySeconds: 10
            periodSeconds: 30
      volumes:
        - name: config-volume
          hostPath:
            path: /mnt/config/prowlarr
            type: DirectoryOrCreate
