apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudbeaver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudbeaver
  template:
    metadata:
      labels:
        app: cloudbeaver
    spec:
      containers:
        - name: cloudbeaver
          image: dbeaver/cloudbeaver:25.1.1
          ports:
            - containerPort: 8978
          volumeMounts:
            - name: cb-data
              mountPath: /opt/cloudbeaver/workspace
      volumes:
        - name: cb-data
          hostPath:
            path: "/mnt/data/cloudbeaver"
            type: DirectoryOrCreate
