apiVersion: v1
kind: Service
metadata:
  name: cloudbeaver
spec:
  selector:
    app: cloudbeaver
  ports:
    - protocol: TCP
      port: 8978
      targetPort: 8978
      nodePort: 31000
  type: NodePort
