apiVersion: v1
kind: Secret
metadata:
  name: immich-postgres-secret
  labels:
    app: immich-postgres
type: Opaque
stringData:
  # CHANGE_ME: password for the immich Postgres superuser
  POSTGRES_PASSWORD: CHANGE_ME
