apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-postgres
  labels:
    app: immich-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: immich-postgres
  template:
    metadata:
      labels:
        app: immich-postgres
    spec:
      containers:
        - name: immich-postgres
          image: tensorchord/pgvecto-rs:pg16-v0.3.0
          imagePullPolicy: Always
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: immich-postgres-config
            - secretRef:
                name: immich-postgres-secret
          resources:
            limits:
              memory: "1Gi"
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          hostPath:
            path: "/mnt/postgresdb-immich"
            type: DirectoryOrCreate
