apiVersion: v1
kind: Secret
metadata:
  name: frigate-secret
  labels:
    app: frigate
type: Opaque
stringData:
  # CHANGE_ME: RTSP password used by Frigate to connect to cameras
  FRIGATE_RTSP_PASSWORD: CHANGE_ME
