apiVersion: v1
kind: Service
metadata:
  labels:
    app: frigate
  name: frigate
spec:
  ports:
    - name: "8971"
      port: 8971
      targetPort: 8971
      nodePort: 31051
    - name: "5000"
      port: 80
      targetPort: 5000
      nodePort: 31052
    - name: "8554"
      port: 8554
      targetPort: 8554
    - name: "8555"
      port: 8555
      targetPort: 8555
    - name: 8555-udp
      port: 8555
      protocol: UDP
      targetPort: 8555
    - name: "1984"
      port: 1984
      targetPort: 1984
      nodePort: 31050
  type: NodePort
  selector:
    app: frigate
