apiVersion: v1
kind: Service
metadata:
  name: oracle-db
spec:
  selector:
    app: oracle-db
  ports:
    - protocol: TCP
      port: 1521
      targetPort: 1521
      nodePort: 32000
  type: NodePort  # Change to ClusterIP or LoadBalancer if needed
