apiVersion: v1
kind: Service
metadata:
  name: mqtt
spec:
  type: NodePort # K3s will assign the host IP here
  selector:
    app: mqtt
  ports:
    - port: 1883
      targetPort: 1883
      nodePort: 31053
      name: mqtt
