apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyseerr
  labels:
    app: jellyseerr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyseerr
  template:
    metadata:
      labels:
        app: jellyseerr
    spec:
      containers:
        - name: jellyseerr
          image: ghcr.io/fallenbagel/jellyseerr:latest
          envFrom:
            - configMapRef:
                name: jellyseerr-config
          volumeMounts:
            - name: config-volume
              mountPath: /app/config
          ports:
            - containerPort: 5055
          livenessProbe:
            httpGet:
              path: /api/v1/status
              port: 5055
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /api/v1/status
              port: 5055
            initialDelaySeconds: 10
            periodSeconds: 30
      volumes:
        - name: config-volume
          hostPath:
            path: /mnt/config/jellyseerr
            type: DirectoryOrCreate
