apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-site
  labels:
    app: static-site
spec:
  replicas: 1
  selector:
    matchLabels:
      app: static-site
  template:
    metadata:
      labels:
        app: static-site
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: html-volume
              mountPath: /usr/share/nginx/html   # default nginx web root
      volumes:
        - name: html-volume
          hostPath:
            path: /mnt/computerhut   # path on your K8s node where HTML/CSS are stored
            type: DirectoryOrCreate
