apiVersion: v1
kind: Secret
metadata:
  name: grafana-secret
  namespace: default
  labels:
    app: grafana
type: Opaque
stringData:
  # CHANGE_ME: initial Grafana admin credentials
  GF_SECURITY_ADMIN_USER: CHANGE_ME
  GF_SECURITY_ADMIN_PASSWORD: CHANGE_ME
