apiVersion: v1
kind: Secret
metadata:
  name: immich-server-secret
  labels:
    app: immich-server
type: Opaque
stringData:
  # CHANGE_ME: must match POSTGRES_PASSWORD in databases/postgres/immich-postgres-secret.yaml
  DB_PASSWORD: CHANGE_ME
