apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-machine-learning
spec:
  replicas: 1
  selector:
    matchLabels:
      app: immich-ml
  template:
    metadata:
      labels:
        app: immich-ml
    spec:
      containers:
        - name: ml
          image: ghcr.io/immich-app/immich-machine-learning:v3.1.0
          ports:
            - containerPort: 3003
