apiVersion: v1
kind: Service
metadata:
  name: go2rtc
spec:
  selector:
    app: go2rtc
  ports:
    - name: uiport
      protocol: TCP
      port: 31060
      targetPort: 31060
    - name: exposertsp
      protocol: TCP
      port: 31061
      targetPort: 31061
    - name: exposertspudp
      protocol: UDP
      port: 31061
      targetPort: 31061
  type: ClusterIP
