apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: default
  labels:
    app: kibana
spec:
  type: NodePort
  selector:
    app: kibana
  ports:
    - name: https
      port: 5601
      targetPort: 5601
