apiVersion: v1
kind: Secret
metadata:
  name: kibana-encryption-keys
  namespace: default
  labels:
    app: kibana
type: Opaque
stringData:
  # CHANGE_ME: each must be a random string of 32+ characters.
  # Generate with e.g.:  openssl rand -hex 32
  XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY: CHANGE_ME
  XPACK_SECURITY_ENCRYPTIONKEY: CHANGE_ME
  XPACK_REPORTING_ENCRYPTIONKEY: CHANGE_ME
