apiVersion: v1
kind: Service
metadata:
  name: inverter-ocr
  labels:
    app: inverter-ocr
spec:
  type: ClusterIP
  selector:
    app: inverter-ocr
  ports:
    - name: http
      port: 5000
      targetPort: 5000
