apiVersion: v1
kind: Secret
metadata:
  name: log-generator-agent-secret
  namespace: default
  labels:
    app: log-generator
type: Opaque
stringData:
  # CHANGE_ME: Elastic Agent enrollment token from Kibana → Fleet UI
  FLEET_ENROLLMENT_TOKEN: CHANGE_ME
